
spring.datasource.url=jdbc:mysql://localhost:3306/book_my_show
spring.datasource.username=root
spring.datasource.password=Root@123

spring.application.name=bookMyshow
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
